[workspace]
members = ["crates/ironflow", "crates/ironflow-macros"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Nikita Moshenskiy <nikita@moshensky>"]
repository = "https://github.com/sparkmill/ironflow"
homepage = "https://github.com/sparkmill/ironflow"
rust-version = "1.89"

[profile.dev]
debug = "line-tables-only"
# NB: Before attaching a debugger this has to be uncommented
# debug = true

[profile.release]
opt-level = "s"    # Optimize for size with good performance balance
lto = "thin"       # Thin LTO - much faster than full LTO, still good optimization
codegen-units = 16 # Parallel compilation for faster builds
strip = true       # Strip symbols to reduce binary size
debug = false      # No debug info in production
panic = "abort"    # Faster panics, smaller binary, immediate container restart in K8s

[workspace.dependencies]
# Local crates
ironflow-macros = { version = "0.1", path = "crates/ironflow-macros" }

# Async runtime
tokio = { version = "1.50", default-features = false, features = [
  "macros",
  "rt-multi-thread",
  "signal",
  "sync",
  "time",
] }
async-trait = "0.1"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling
thiserror = "2.0"
anyhow = "1.0"

# Data
# NB! Keep in sync with the one in `./scripts/sqlx_install.sh`
sqlx = { version = "0.8", default-features = false, features = [
  "runtime-tokio",
  "tls-rustls-aws-lc-rs",
  "postgres",
  "derive",
  "macros",
  "migrate",
  "uuid",
  "time",
  "json",
] }
url = "2.5"
uuid = { version = "1.22", features = ["v4", "v7", "serde"] }
nonempty = { version = "0.12", features = ["std", "serialize"] }

# Date and time
time = { version = "0.3", features = [
  "serde",
  "serde-human-readable",
  "macros",
  "formatting",
  "parsing",
] }

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Configuration
dotenvy = "0.15"

# Other
reqwest = { version = "0.13", default-features = false, features = [
  "json",
  "rustls",
  "cookies",
  "form",
  "query",
] }

[profile.dev.package.sqlx-macros]
opt-level = 3
